### ISSUE TITLE
Migrate to Maven Central

### ISSUE THREAD

**Issue by L3K0V** [ttlock/Android_SDK_Demo#12]
JFrog have announced that they'll be shutting down JCenter: https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

Starting from 1st of May Bintray and JCenter services are no longer available. Hence, TTLock SDK should also be migrated to another maven repository like Maven central.

**Comment by sinhaDroid** [comment]
let me know when it can be integrated. Currently, we are not able to use ttlock.

**Comment by L3K0V** [comment]
You can still use the `jcenter()` as they reported to leave it read-only but there will no accept new versions
