### ISSUE TITLE
is it possible to add locks and add locks only through the SDK?

### ISSUE THREAD

**Issue by PronenkoDmitry** [ttlock/Android_SDK_Demo#13]
Hi guys. Is the addition of gateways carried out only through the SDK? I did not find a description of the API methods in the documentation there is only for SDK.

**Comment by PronenkoDmitry** [comment]
не помогли...

**Comment by Stroesku** [comment]
@PronenkoDmitry ты разобрался? можешь и мне помочь, я по их документации вообще ниче не могу понять
