### ISSUE TITLE
Cannot specify type of the passcode

### ISSUE THREAD

**Issue by L3K0V** [ttlock/Android_SDK_Demo#2]
Cannot create 

- [ ] permanent
- [ ] count
- [ ] cycle

 passcodes from the new SDK.

`createCustomPasscode` `modifyCustomPasscode` and `modifyAdminPasscode` are the only methods for configuring passcodes. There's no method argument specifying the type of the passcode. I think this is very important and must to have functionality.

The old SDK have them and support them also the TTLock official app. But the old SDK is not longer supported on Android 9 because of the Bluetooth services implemented and permissions.

**Comment by ttlock** [comment]
specify type of passcode is get from TTLock open platform by call server api.   the website :+1: https://open.sciener.cn/doc/api/v3/keyboardPwd/get
